<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>


	<ItemGroup>
		<Compile Include="..\..\Project_Mouse_3D_URP\Assets\Scripts\Framework_Core\**\*.cs">
			<Link>%(RecursiveDir)%(FileName)%(Extension)</Link>
		</Compile>
	</ItemGroup>

	<ItemGroup>
    <PackageReference Include="K4os.Compression.LZ4" Version="1.3.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Project_Mouse_General_Function\Project_Mouse_Core_Tools.csproj" />
  </ItemGroup>

</Project>
