<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <StartupObject>CLIP.Server.Server_Main_ver_02</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClickableTransparentOverlay" Version="11.1.0" />
    <PackageReference Include="Fleck" Version="1.2.0" />
    <PackageReference Include="ImGui.NET" Version="1.91.6.1" />
    <PackageReference Include="Microsoft.AspNetCore" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.ResponseCompression" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.3.0" />
    <PackageReference Include="Microsoft.Orleans.Sdk" Version="9.1.2" />
    <PackageReference Include="Microsoft.Orleans.Serialization.NewtonsoftJson" Version="9.1.2" />
    <PackageReference Include="Microsoft.Orleans.Server" Version="9.1.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Npgsql" Version="9.0.3" />
    <PackageReference Include="Serilog" Version="4.2.0" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
    <PackageReference Include="System.Security.Cryptography.X509Certificates" Version="4.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CLIP_Project_Mouse_Kernel\CLIP_Project_Mouse_Kernel.csproj" />
    <ProjectReference Include="..\Project_Mouse_DataLoader\Project_Mouse_DataLoader.csproj" />
    <ProjectReference Include="..\Project_Mouse_GameLogic\Project_Mouse_GameLogic.csproj" />
    <ProjectReference Include="..\Project_Mouse_Grains_Implementation\Project_Mouse_Grains_Implementation.csproj" />
    <ProjectReference Include="..\Project_Mouse_Grains_Interfaces\Project_Mouse_Grains_Interfaces.csproj" />
    <ProjectReference Include="..\Project_Mouse_Grain_Helper_Lib\Project_Mouse_Grain_Helper_Lib.csproj" />
    <ProjectReference Include="..\Project_Mouse_Server_Event_System\Project_Mouse_Server_Event_System.csproj" />
    <ProjectReference Include="..\Project_Mouse_Server_IMGUI\Project_Mouse_Server_IMGUI.csproj" />
    <ProjectReference Include="..\Project_Mouse_Server_Network\Project_Mouse_Server_Network.csproj" />
  </ItemGroup>


</Project>
