<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

 

  <ItemGroup>
    <PackageReference Include="Fleck" Version="1.2.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Npgsql" Version="9.0.3" />
    <PackageReference Include="System.Security.Cryptography.X509Certificates" Version="4.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CLIP_Project_Mouse_Kernel\CLIP_Project_Mouse_Kernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="websocket-sharp">
      <HintPath>..\External\websocket-sharp.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
