<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Orleans.Sdk" Version="9.1.2" />
    <PackageReference Include="Microsoft.Orleans.Serialization.NewtonsoftJson" Version="9.1.2" />
    <PackageReference Include="Microsoft.Orleans.Server" Version="9.1.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CLIP_Project_Mouse_Kernel\CLIP_Project_Mouse_Kernel.csproj" />
    <ProjectReference Include="..\Project_Mouse_GameLogic\Project_Mouse_GameLogic.csproj" />
    <ProjectReference Include="..\Project_Mouse_General_Function\Project_Mouse_Core_Tools.csproj" />
    <ProjectReference Include="..\Project_Mouse_Grains_Interfaces\Project_Mouse_Grains_Interfaces.csproj" />
    <ProjectReference Include="..\Project_Mouse_Grain_Helper_Lib\Project_Mouse_Grain_Helper_Lib.csproj" />
    <ProjectReference Include="..\Project_Mouse_Server_Event_System\Project_Mouse_Server_Event_System.csproj" />
	  <ProjectReference Include="..\Project_Mouse_DataLoader\Project_Mouse_DataLoader.csproj" />
  </ItemGroup>

</Project>
